### ISSUE TITLE
Invalid column name 'AccountNameRegex'

### ISSUE THREAD

**Issue by ToddTaylor** [DavidCBerry13/FoodTruckNationApi#1]
When I run this project for the first time and attempt to request a full list of food trucks, I get the following error:

> FoodTruckNation.Core.AppServices.FoodTruckService|ERROR|Error thrown while calling FoodTruckService.GetAllFoodTrucks() System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'AccountNameRegex'.

To resolve this error, I commented-out the property **AccountNameRegex** in both the **SocialMediaPlatformModel** class and the **SocialMediaPlatform** class.  Both properties had zero references, so perhaps these properties were going to be part of a feature that wasn't implemented?

**Comment by DavidCBerry13** [comment]
Thanks Todd.  What you did works as the column isn't critical.

What the real issue is was that the column was missing from the table creation script in the database project.  I had added it in the database but forgot to put it in the script.  Just committed that change now, so you can grab it or keep doing what you are doing, but at least no one else should run into this issue.
